Турсунов Темирлан
su5kk/react_hse_hw pull request #3
Opened 2020-10-15 21:43 UTC by su5kk

2020-10-18 14:06 UTC, ValeryStatinov requested changes
в мастере папка hw3_tt, а здесь hw3_TT. + лишняя поддиректория tim_task_tracker. все эти папки не нужны, в корне проекта должны лежать файлы package.json, package-lock.json, src/ и тд. этот репозиторий не только для hw3, но и для всех остальных домашек.

уверен, что на 3-ий раз все получится!:)

2020-10-18 14:07 UTC, ValeryStatinov commented
PS в дедлайн ты попал, осталось привести репозиторий в порядок и дз будет проверена

2020-10-18 14:47 UTC, su5kk commented
> в мастере папка hw3_tt, а здесь hw3_TT. + лишняя поддиректория tim_task_tracker. все эти папки не нужны, в корне проекта должны лежать файлы package.json, package-lock.json, src/ и тд. этот репозиторий не только для hw3, но и для всех остальных домашек.
> 
> уверен, что на 3-ий раз все получится!:)

т.е. мне нужно мне нужно, грубо говоря, вытащить все файлы из tim_task_tracker наружу и удалить hw3_TT и tim_task_tracker?

2020-10-18 14:49 UTC, ValeryStatinov commented
> > в мастере папка hw3_tt, а здесь hw3_TT. + лишняя поддиректория tim_task_tracker. все эти папки не нужны, в корне проекта должны лежать файлы package.json, package-lock.json, src/ и тд. этот репозиторий не только для hw3, но и для всех остальных домашек.
> > уверен, что на 3-ий раз все получится!:)
> 
> т.е. мне нужно мне нужно, грубо говоря, вытащить все файлы из tim_task_tracker наружу и удалить hw3_TT и tim_task_tracker?

ага

2020-10-20 14:56 UTC, ValeryStatinov requested changes
отлично!
остался последний шаг - новым коммитом удалить из ветки папку `hw3_tt`, чтобы ее не было в репозитории

2020-10-20 14:56 UTC, ValeryStatinov commented on src/components/item.jsx
> +        console.log("The " + ID + " task is completed. Status is: " + completeness);
всегда будет выводить только `true` из-аз if'a выше, но ничего страшного.

2020-10-20 14:56 UTC, ValeryStatinov commented on src/components/MyToDoList.js
> +            {this.state.tasks.map(task => <Item task = {task}/>)}
не хватает отступа

2020-10-20 15:10 UTC, su5kk commented on src/components/MyToDoList.js
> +            {this.state.tasks.map(task => <Item task = {task}/>)}
Отступа в плане кодстайла или отступа у какого-то элемента? Не совсем понимаю

2020-10-20 15:12 UTC, ValeryStatinov commented on src/components/MyToDoList.js
> +            {this.state.tasks.map(task => <Item task = {task}/>)}
да, в плане код стайла

2020-10-22 21:40 UTC, ValeryStatinov approved these changes
отл(9)

2020-10-22 21:40 UTC, ValeryStatinov commented on src/components/MyToDoList.js
> +            {this.state.tasks.map(task => <Item task = {task}/>)}
коммент resolved, а отступа не появилось)

2020-10-22 21:40 UTC, merged